"""Third migration changed name of classes

Revision ID: 23d2cde03615
Revises: 29fa523f1ff7
Create Date: 2018-09-07 17:32:44.401766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23d2cde03615'
down_revision = '29fa523f1ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.drop_column('categories', 'description')
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('post_comment', sa.String(length=255), nullable=True))
    op.add_column('comments', sa.Column('time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_post_comment'), 'comments', ['post_comment'], unique=False)
    op.create_foreign_key(None, 'comments', 'pitches', ['pitch_id'], ['id'])
    op.drop_column('comments', 'commentcontent')
    op.drop_column('comments', 'postedat')
    op.add_column('pitches', sa.Column('post', sa.String(length=300), nullable=True))
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pitches_post'), 'pitches', ['post'], unique=False)
    op.drop_column('pitches', 'pitchcontent')
    op.drop_column('pitches', 'time_posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('time_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitchcontent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pitches_post'), table_name='pitches')
    op.drop_column('pitches', 'time')
    op.drop_column('pitches', 'post')
    op.add_column('comments', sa.Column('postedat', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('commentcontent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_post_comment'), table_name='comments')
    op.drop_column('comments', 'time')
    op.drop_column('comments', 'post_comment')
    op.drop_column('comments', 'pitch_id')
    op.add_column('categories', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    # ### end Alembic commands ###
